# render.yaml
#
# Defines two PostgreSQL databases and one MinIO service.
# This version correctly pulls the public MinIO Docker image.

databases:
  - name: nextjs-db
    plan: free

  - name: python-db
    plan: free

services:
  # ------------------
  # MinIO Instance
  # ------------------
  - type: pserv
    name: minio
    image:
      url: minio/minio
    command: server /data --console-address ":9001"
    envVars:
      - key: MINIO_ROOT_USER
        generateValue: true
      - key: MINIO_ROOT_PASSWORD
        generateValue: true
      - key: MINIO_DEFAULT_BUCKETS
        value: "main"
    disk:
      name: minio-data
      mountPath: /data
      sizeGB: 1
