# render.yaml 
#
# Defines two PostgreSQL databases and one MinIO service.
# Databases are defined under the top-level 'databases' key.
# MinIO is a private service and remains under the 'services' key.

databases:
  - name: postgres-db-1
    plan: free 

  - name: postgres-db-2
    plan: free

services:
  # ------------------
  # MinIO Instance
  # ------------------
  - type: pserv
    name: minio
    env: docker
    envVars:
      - key: MINIO_ROOT_USER
        generateValue: true
      - key: MINIO_ROOT_PASSWORD
        generateValue: true
      - key: MINIO_DEFAULT_BUCKETS
        value: "main"
    disk:
      name: minio-data
      mountPath: /data
      sizeGB: 1
